name: unity_test
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  camera: null
  change_app_package_name: null
  cupertino_icons: null
  dartz: ^0.10.1
  firebase_messaging: 
  firebase_core:
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_form_builder: null
  flutter_screenutil: ^5.9.3
  flutter_svg: null
  fluttertoast: null
  gap: ^3.0.1
  google_mlkit_text_recognition: null
  http: null
  image_picker: ^1.1.2
  intl: ^0.20.2
  page_transition: null
  provider: null
  pusher_client: 
  shared_preferences: null
  skeletonizer: ^1.4.3
  top_snackbar_flutter: null
  web_socket_channel: null
  geolocator: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/LOGO-NEW.png"


flutter:
  uses-material-design: true
  assets:
    - assets/images/Logo.png
    - assets/images/ypu-2011_0517.jpg
    - assets/images/User.png
    - assets/images/admission.jpg
