// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTFKDH_F7xBQXn7-eu1dxDsEkjMH_CtQ8',
    appId: '1:462633142007:web:1339e51929a4ea43b7b5f2',
    messagingSenderId: '462633142007',
    projectId: 'unitytest-c41ef',
    authDomain: 'unitytest-c41ef.firebaseapp.com',
    storageBucket: 'unitytest-c41ef.firebasestorage.app',
    measurementId: 'G-KLJR7YYZCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHMGPWO10gEzJMZKBstCu47z3JkptVI18',
    appId: '1:462633142007:android:e2f9e496003e3cfeb7b5f2',
    messagingSenderId: '462633142007',
    projectId: 'unitytest-c41ef',
    storageBucket: 'unitytest-c41ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR8qQU3zMkHKMoBfwSzTnBy5uTwgSbZ5s',
    appId: '1:462633142007:ios:a18b3a6784ae936db7b5f2',
    messagingSenderId: '462633142007',
    projectId: 'unitytest-c41ef',
    storageBucket: 'unitytest-c41ef.firebasestorage.app',
    iosBundleId: 'com.example.unityTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR8qQU3zMkHKMoBfwSzTnBy5uTwgSbZ5s',
    appId: '1:462633142007:ios:a18b3a6784ae936db7b5f2',
    messagingSenderId: '462633142007',
    projectId: 'unitytest-c41ef',
    storageBucket: 'unitytest-c41ef.firebasestorage.app',
    iosBundleId: 'com.example.unityTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTFKDH_F7xBQXn7-eu1dxDsEkjMH_CtQ8',
    appId: '1:462633142007:web:ffbf35d0c4f1f6d8b7b5f2',
    messagingSenderId: '462633142007',
    projectId: 'unitytest-c41ef',
    authDomain: 'unitytest-c41ef.firebaseapp.com',
    storageBucket: 'unitytest-c41ef.firebasestorage.app',
    measurementId: 'G-WB8D8CHDV2',
  );
}
